apiVersion: v1
kind: Namespace
metadata:
  name: ai-schedule-manager
  labels:
    name: ai-schedule-manager
    environment: production
    app: ai-schedule-manager
    version: v1
  annotations:
    description: "AI Schedule Manager application namespace"
    contact: "admin@yourdomain.com"
---
# Resource Quotas for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-schedule-manager-quota
  namespace: ai-schedule-manager
spec:
  hard:
    # Compute resources
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi

    # Storage resources
    requests.storage: 200Gi
    persistentvolumeclaims: "10"

    # Object counts
    pods: "50"
    services: "20"
    secrets: "20"
    configmaps: "20"
    replicationcontrollers: "10"
    deployments.apps: "10"
    statefulsets.apps: "5"
    jobs.batch: "10"
    cronjobs.batch: "5"
---
# Limit Ranges for pods
apiVersion: v1
kind: LimitRange
metadata:
  name: ai-schedule-manager-limits
  namespace: ai-schedule-manager
spec:
  limits:
  - type: Pod
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 50m
      memory: 64Mi
  - type: Container
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 50m
      memory: 64Mi
  - type: PersistentVolumeClaim
    max:
      storage: 100Gi
    min:
      storage: 1Gi
---
# Network Policy for namespace isolation
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ai-schedule-manager-network-policy
  namespace: ai-schedule-manager
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  # Allow ingress from monitoring namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
  # Allow internal communication within namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: ai-schedule-manager
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow HTTPS to external services
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP to external services (for development)
  - to: []
    ports:
    - protocol: TCP
      port: 80
  # Allow internal communication
  - to:
    - namespaceSelector:
        matchLabels:
          name: ai-schedule-manager