apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-schedule-frontend
  namespace: ai-schedule-manager
  labels:
    app: ai-schedule-frontend
    version: v1
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-schedule-frontend
  template:
    metadata:
      labels:
        app: ai-schedule-frontend
        version: v1
        tier: frontend
    spec:
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      containers:
      - name: frontend
        image: ai-schedule-manager-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api-url
        - name: REACT_APP_ENVIRONMENT
          value: "production"
        - name: REACT_APP_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: frontend-sentry-dsn
              optional: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-schedule-frontend-hpa
  namespace: ai-schedule-manager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-schedule-frontend
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30